language: java
sudo: true
jdk: openjdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - chmod +x mvnw
  - chmod +x runme
script: ./runme
# safelist
branches:
  only:
    - main